SELECT
FORMAT_DATE('%A', DATE(SENT)) AS Day,

EXTRACT(DAYOFWEEK FROM DATE(SENT)) AS Day_Number,

EXTRACT(HOUR FROM SENT) AS Hour,

CASE
  WHEN EXTRACT(HOUR FROM SENT) = 0 THEN '12 AM'
  WHEN EXTRACT(HOUR FROM SENT) < 12
    THEN CONCAT(CAST(EXTRACT(HOUR FROM SENT) AS STRING),' AM')
  WHEN EXTRACT(HOUR FROM SENT) = 12 THEN '12 PM'
  ELSE CONCAT(CAST(EXTRACT(HOUR FROM SENT)-12 AS STRING),' PM')
END AS Hour_Label,

CASE
  WHEN EXTRACT(HOUR FROM SENT) BETWEEN 4 AND 7 THEN 'Early Morning'
  WHEN EXTRACT(HOUR FROM SENT) BETWEEN 8 AND 11 THEN 'Morning'
  WHEN EXTRACT(HOUR FROM SENT) BETWEEN 12 AND 15 THEN 'Afternoon'
  WHEN EXTRACT(HOUR FROM SENT) BETWEEN 16 AND 19 THEN 'Evening'
  WHEN EXTRACT(HOUR FROM SENT) BETWEEN 20 AND 23 THEN 'Night'
  ELSE 'Late Night'
END AS Time_Bucket,

CASE
  WHEN EXTRACT(HOUR FROM SENT) BETWEEN 4 AND 7 THEN 1
  WHEN EXTRACT(HOUR FROM SENT) BETWEEN 8 AND 11 THEN 2
  WHEN EXTRACT(HOUR FROM SENT) BETWEEN 12 AND 15 THEN 3
  WHEN EXTRACT(HOUR FROM SENT) BETWEEN 16 AND 19 THEN 4
  WHEN EXTRACT(HOUR FROM SENT) BETWEEN 20 AND 23 THEN 5
  ELSE 6
END AS Time_Order,

COUNT(*) AS Sent_Count,

COUNTIF(READ IS NOT NULL) AS Read_Count,

ROUND(
  SAFE_DIVIDE(COUNTIF(READ IS NOT NULL), COUNT(*)) * 100,
  2
) AS Read_Percent

FROM `whatsappanalysis-487206.Best_day_time.6_month_data`

GROUP BY
Day,
Day_Number,
Hour,
Hour_Label,
Time_Bucket,
Time_Order

ORDER BY
Day_Number,
Time_Order,
Hour;
